name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ruby: ['3.0', '3.1', '3.2', '3.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install package dependencies
        run: "[ -e $APT_DEPS ] || sudo apt-get install -y --no-install-recommends $APT_DEPS"
        env:
          APT_DEPS: "imagemagick"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec
